<script>
// Generated by: php artisan freescout:module-build
// Keep this file CSP-safe (no inline event handlers, no external dependencies).
window.OVERFLOWACHIEVEMENT_ENABLED = {{ \Option::get('overflowachievement.enabled', config('overflowachievement.enabled') ? 1 : 0) ? 'true' : 'false' }};

// Endpoints (include subdirectory automatically via route()).
window.OVERFLOWACHIEVEMENT_UNSEEN_URL = "{{ route('overflowachievement.unseen') }}";
window.OVERFLOWACHIEVEMENT_MARK_SEEN_URL = "{{ route('overflowachievement.mark_seen') }}";

// UI configuration (mirrors Settings values)
window.OVERFLOWACHIEVEMENT_UI = {
  confetti: {{ \Option::get('overflowachievement.ui.confetti', 1) ? 'true' : 'false' }},
  effect: "{{ (string)\Option::get('overflowachievement.ui.effect', 'confetti') }}",
  toast_theme: "{{ (string)\Option::get('overflowachievement.ui.toast_theme', 'neon') }}",
  sound_enabled: {{ \Option::get('overflowachievement.ui.sound_enabled', config('overflowachievement.ui.sound_enabled') ? 1 : 0) ? 'true' : 'false' }},
  sound_cooldown_ms: {{ (int)\Option::get('overflowachievement.ui.sound_cooldown_ms', (int)config('overflowachievement.ui.sound_cooldown_ms', 1200)) }},
  toast_sticky: {{ \Option::get('overflowachievement.ui.toast_sticky', 0) ? 'true' : 'false' }},
  toast_duration_ms: {{ (int)\Option::get('overflowachievement.ui.toast_duration_ms', 10000) }},
  toast_stack_enabled: {{ \Option::get('overflowachievement.ui.toast_stack_enabled', 0) ? 'true' : 'false' }},
  toast_stack_max: {{ (int)\Option::get('overflowachievement.ui.toast_stack_max', 2) }},
};

// UI strings for client-side toasts (kept tiny on purpose).
// Fallbacks exist in JS in case vars.js is not generated.
window.OVERFLOWACHIEVEMENT_I18N = {
  level_up: "{{ __('Level Up!') }}",
  trophy_unlocked: "{{ __('Trophy Unlocked') }}",
  achievements_unlocked: "{{ __('Achievements Unlocked') }}",
  achievements_count: "{{ __('+:count achievements', ['count' => ':count']) }}",
  queued: "{{ __('queued') }}",
  unlocked_list: "{{ __('Unlocked') }}",
  unlocked: "{{ __('Unlocked') }}",
  locked: "{{ __('Locked') }}",
  preview_title: "{{ __('Achievement Preview') }}",
};

// Trigger labels/hints/scopes for the achievements UI.
window.OVERFLOWACHIEVEMENT_TRIGGERS = {
  labels: {!! json_encode(config('overflowachievement.triggers.labels', [])) !!},
  hints: {!! json_encode(config('overflowachievement.triggers.hints', [])) !!},
  scopes: {!! json_encode(config('overflowachievement.triggers.scopes', [])) !!},
  scope_labels: {
    lifetime: "{{ __('Lifetime') }}",
    daily: "{{ __('Daily') }}",
    per_conversation: "{{ __('Per conversation') }}",
  }
};
</script>
